name: Deploy Vite Frontend to Firebase Hosting

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend  # important: your app is in /frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Vite project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy \
            --only hosting \
            --config frontend/firebase.json \
            --project my-vite-frontend \
            --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}"
